spring.application.name=coach
spring.datasource.url=jdbc:postgresql://localhost:5432/swimcoach
spring.datasource.username=postgres
spring.datasource.password=0000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thymeleaf.cache=false